services:
  db:
    image: postgres:15
    container_name: my_project_db
    environment:
      POSTGRES_USER: student1
      POSTGRES_PASSWORD: student123
      POSTGRES_DB: projectdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./lost_found_database.sql:/docker-entrypoint-initdb.d/lost_found_database.sql
    networks:
      - lostfound_network

  app:
    build: .
    container_name: umbc_lost_found_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: projectdb
      DB_USER: student1
      DB_PASSWORD: student123
    networks:
      - lostfound_network

volumes:
  db_data:

networks:
  lostfound_network:
    driver: bridge